### ISSUE TITLE
Is this plugin still in development? 

### ISSUE THREAD

**Issue by Sebastian1989101** [aspnetde/MvvmNano#19]
@aspnetde  Some user requests here are pretty old and the MvvmNano library seems not finished because there are so many problems with it. 

1. Global Styles from the App.xaml are not working on iOS. 
2. The Navigation is totally broken if you want to use modal dialogs (also there are no examples for that) 
3. It is impossible to display alerts for the user.

**Comment by aspnetde** [comment]
I am no longer actively maintaining this framework, but I am in talks about transferring the ownership. So there might be a future.

2. Wrong. Use the presenter for it. There you can do whatever you want.

3. Wrong. The framework doesn't care about alerts, this is completely up to you. And doing so is easy. Create an interface IAlert with a method Show(), inject this in your view model and implement it a) for all platforms with XF, or b) on each platform individually.

Claiming it is totally broken is just nonsense.

**Comment by krdmllr** [comment]
@Sebastian1989101 to your first problem., do you have the same error described in this issue: https://github.com/aspnetde/MvvmNano/issues/18 ?

**Comment by krdmllr** [comment]
I will close this issue since i was not able to   the stated problem and @Sebastian1989101 did not provide any examples. Please open an issue if you have any problems with MvvmNano.

Concerning your question wether MvvmNano is still in development, yes it is. I maintain the code and add missing features if needed.
